[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["python backend/create_database.py"]

[start]
cmd = "gunicorn -k eventlet -w 1 --chdir backend app:app --bind 0.0.0.0:$PORT"
